#!/usr/bin/env bash
echo "killing puma: sudo pkill -9 -f puma"
sudo pkill -9 -f puma
echo "puma killed. Waiting for 5s before restarting.."
sleep 5s
echo "restarting puma.."
killall ruby
source ~/.bash_profile
rbenv shell 2.3.3
bundle install
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production bundle exec rake assets:precompile
bundle exec puma -e production 1> /var/www/nusskylab/log/console.log 2> /var/www/nusskylab/log/console_err.log &
